apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default.policy3
spec:
  egress:
    - action: Allow
      destination: {}
      source: {}
  ingress:
    - action: Allow
      destination: {}
      source: {}
  tier: default
  types:
    - Ingress
    - Egress
