apiVersion: projectcalico.org/v3
kind: StagedNetworkPolicy
metadata:
  name: security.staged-sec-policy3
  namespace: calico-system
spec:
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
  egress:
    - action: Allow
