apiVersion: projectcalico.org/v3
kind: StagedNetworkPolicy
metadata:
  name: default.staged-policy1
  namespace: calico-system
spec:
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
  egress:
    - action: Allow
