apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  tier: namespace-isolation
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      source: { }
      destination: { }
  egress:
    - action: Allow
      source: { }
      destination: { }
