apiVersion: projectcalico.org/v3
kind: StagedKubernetesNetworkPolicy
metadata:
  name: allow-all
  namespace: argocd
spec:
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
